---

- hosts: proxmox
  gather_facts: true
  become: yes
  roles:
    - role: proxmox_lxc
      when: proxmox_lxc_configure
  tags:
     - k3s-init
     
- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: lxc
      become: true
      when: proxmox_lxc_configure
    - role: prereq
      become: true
    - role: download
      become: true
    - role: raspberrypi
      become: true
  tags:
     - k3s-init

- hosts: master
  roles:
    - role: k3s/master
      become: true
  tags:
     - k3s-init

- hosts: node
  roles:
    - role: k3s/node
      become: true
  tags:
     - k3s-init

- hosts: master
  roles:
    - role: k3s/post
      become: true

- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: reboot
  tags:
     - k3s-init


- hosts: localhost
  gather_facts: false
  connection: local
  roles:
   - role: cert-manager
  tags:
     - certmanager

- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: traefik
  tags:
     - traefik
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: reflector
  tags:
     - reflector
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: rancher
  tags:
     - rancher
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: argocd
  tags:
     - argocd

- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: longhorn
  tags:
     - longhorn
