---

- hosts: proxmox
  gather_facts: true
  become: yes
  roles:
    - role: proxmox_lxc
      when: proxmox_lxc_configure
  tags:
     - k3s-init
     - provision-cluster

- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: lxc
      become: true
      when: proxmox_lxc_configure
    - role: prereq
      become: true
    - role: download
      become: true
    - role: raspberrypi
      become: true
  tags:
     - k3s-init
     - provision-cluster

- hosts: master
  roles:
    - role: k3s/master
      become: true
  tags:
     - k3s-init
     - provision-cluster

- hosts: node
  roles:
    - role: k3s/node
      become: true
  tags:
     - k3s-init
     - provision-cluster

- hosts: master
  roles:
    - role: k3s/post
      become: true
  tags:
     - k3s-init
     - provision-cluster
     - master-post

- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: reboot
  tags:
     - k3s-init
     - provision-cluster
     - reboot

- hosts: master[0]
  roles:
   - role: kubeconfig
  tags:
     - kubeconfig
     - provision-cluster

- hosts: localhost
  gather_facts: false
  connection: local
  roles:
   - role: cert-manager
  tags:
     - certmanager
     - provision-cluster

- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: traefik
  tags:
     - traefik
     - provision-cluster
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: reflector
  tags:
     - reflector
     - provision-cluster
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: rancher
  tags:
     - rancher
     - provision-cluster
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: argocd
  tags:
     - argocd
     - provision-cluster

- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - role: longhorn
  tags:
     - longhorn
