
- name: Add Rancher stable chart repo
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: "https://releases.rancher.com/server-charts/stable"

- name: wait for k3s API server VIP {{ apiserver_endpoint }} to be available
  wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    delay: 5

- name: Deploy version of rancher helm chart inside cattle-system namespace (and create it)
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-stable/rancher
    release_namespace: cattle-system
    create_namespace: true
    update_repo_cache: True
    values: "{{ lookup('template', 'values.yml.j2') | from_yaml }}"

- name: Apply rancher ingress .
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.yml.j2') | from_yaml }}"
