
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: wait for k3s API server VIP {{ apiserver_endpoint }} to be available
  wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    delay: 5

- name: Apply cert-manager manifest to the cluster.
  kubernetes.core.k8s:
    state: absent
    src: https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml


- name: Apply cert-manager manifest to the cluster.
  kubernetes.core.k8s:
    state: present
    src: https://github.com/cert-manager/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.crds.yaml

- name: Remove test release and waiting suppression ending
  kubernetes.core.helm:
    name: cert-manager
    state: absent
    release_namespace: monitoring

- name: Deploy version of Cert-Manager chart inside cert-manager namespace (and create it)
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: True
    values: "{{ lookup('template', 'values.yml.j2') | from_yaml }}"

- name: Apply cert-manager cloudflare secret.
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'cloudflare-token-secret.yml.j2') | from_yaml }}"

- name: Apply cert-manager letsencrypt-production secret.
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'letsencrypt-production.yml.j2') | from_yaml }}"

- name: Apply cert-manager letsencrypt-staging secret.
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'letsencrypt-staging.yml.j2') | from_yaml }}"


- name: Apply cert-manager internal-tls secret.
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'internal-tls.yml.j2') | from_yaml }}"
