---


- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "https://helm.traefik.io/traefik"

- name: wait for k3s API server VIP {{ apiserver_endpoint }} to be available
  wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    delay: 5

- name: Deploy version of traefik chart inside traefik namespace (and create it)
  kubernetes.core.helm:
    name: traefik-internal
    chart_ref: traefik/traefik
    release_namespace: traefik
    create_namespace: true
    update_repo_cache: True
    values: "{{ lookup('template', 'values.yml.j2') | from_yaml }}"


- name: Apply traefik default-headers middleware.
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'default-headers.yml.j2') | from_yaml }}"

- name: Apply traefik dashboard secret.
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'dashboard-secret.yml.j2') | from_yaml }}"

- name: Apply traefik ingress .
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.yml.j2') | from_yaml }}"
