---
- name: Create traefik config directory on first master
  file:
    path: /tmp/traefik
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy traefik internal chart values to first master
  template:
    src: "values.yml.j2"
    dest: /tmp/traefik/values.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Copy traefik default headers to first master
  template:
    src: "default-headers.yml.j2"
    dest: /tmp/traefik/default-headers.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Copy traefik dashboard secret to first master
  template:
    src: "dashboard-secret.yml.j2"
    dest: /tmp/traefik/dashboard-secret.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Copy traefik dashboard ingress to first master
  template:
    src: "ingress.yml.j2"
    dest: /tmp/traefik/ingress.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: add traefik helm repo
  command:
    cmd: "helm repo add traefik https://helm.traefik.io/traefik"
  changed_when: true

- name: update helm repo
  command:
    cmd: "helm repo update"
  changed_when: true

- name: wait for k3s API server VIP {{ apiserver_endpoint }} to be available
  wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    delay: 10

- name: create traefik namespace
  command:
    cmd: "kubectl create namespace traefik"
  changed_when: true

- name: deploy traefik internal using helm
  command:
    cmd: "helm install traefik-internal traefik/traefik \
      --namespace=traefik \
      --values=/tmp/traefik/values.yml"
  changed_when: true

- name: apply traefik default headers
  command:
    cmd: kubectl apply -f /tmp/traefik/default-headers.yml
  changed_when: true

- name: apply traefik dashboard secret
  command:
    cmd: kubectl apply -f /tmp/traefik/dashboard-secret.yml
  changed_when: true

- name: apply traefik dashboard ingressroute
  command:
    cmd: kubectl apply -f /tmp/traefik/ingress.yml
  changed_when: true

- name: Clean up traefik tmp dir
  file:
    path: /tmp/traefik/
    state: absent 
